export const customersData = [
  {
    id: "#CUST001",
    name: "Rahul Sharma",
    email: "rahul@gmail.com",
    phone: "9876543210",
    orders: 12,
    spent: "₹3200",
    status: "Active",
    delivery: {
      boyName: "Aman Verma",
      boyId: "#DB001",
      lastOrderId: "#ORD003",
    },
  },
  {
    id: "#CUST002",
    name: "Anjali Verma",
    email: "anjali@gmail.com",
    phone: "9123456780",
    orders: 5,
    spent: "₹1200",
    status: "Active",
    delivery: {
      boyName: "Rohit Singh",
      boyId: "#DB002",
      lastOrderId: "#ORD002",
    },
  },
  {
    id: "#CUST003",
    name: "Amit Singh",
    email: "amit@gmail.com",
    phone: "9988776655",
    orders: 8,
    spent: "₹2100",
    status: "Inactive",
    delivery: {
      boyName: "Suresh Yadav",
      boyId: "#DB003",
      lastOrderId: "#ORD004",
    },
  },
  {
    id: "#CUST004",
    name: "Neha Gupta",
    email: "neha@gmail.com",
    phone: "9012345678",
    orders: 15,
    spent: "₹4500",
    status: "Active",
    delivery: {
      boyName: "Vikas Kumar",
      boyId: "#DB004",
      lastOrderId: "#ORD001",
    },
  },
  {
    id: "#CUST005",
    name: "Vikram Patel",
    email: "vikram@gmail.com",
    phone: "7894561230",
    orders: 3,
    spent: "₹800",
    status: "Inactive",
    delivery: {
      boyName: "Aman Verma",
      boyId: "#DB001",
      lastOrderId: "#ORD005",
    },
  },
  {
    id: "#CUST006",
    name: "Priya Mehta",
    email: "priya@gmail.com",
    phone: "8765432190",
    orders: 20,
    spent: "₹6800",
    status: "Active",
    delivery: {
      boyName: "Rohit Singh",
      boyId: "#DB002",
      lastOrderId: "#ORD006",
    },
  },
];