export const paymentsData = [
  {
    transactionId: "#TXN1001",
    orderId: "#ORD101",
    customer: "Rahul Sharma",
    email: "rahul@gmail.com",
    method: "UPI",
    amount: "₹450",
    status: "Paid",
    date: "12 May 2026",
  },
  {
    transactionId: "#TXN1002",
    orderId: "#ORD102",
    customer: "Priya Verma",
    email: "priya@gmail.com",
    method: "Card",
    amount: "₹820",
    status: "Pending",
    date: "11 May 2026",
  },
  {
    transactionId: "#TXN1003",
    orderId: "#ORD103",
    customer: "Amit Singh",
    email: "amit@gmail.com",
    method: "UPI",
    amount: "₹299",
    status: "Failed",
    date: "10 May 2026",
  },
  {
    transactionId: "#TXN1004",
    orderId: "#ORD104",
    customer: "Sneha Patel",
    email: "sneha@gmail.com",
    method: "Card",
    amount: "₹999",
    status: "Paid",
    date: "09 May 2026",
  },
  {
    transactionId: "#TXN1005",
    orderId: "#ORD105",
    customer: "Karan Mehta",
    email: "karan@gmail.com",
    method: "UPI",
    amount: "₹540",
    status: "Paid",
    date: "08 May 2026",
  },
];